### ISSUE TITLE
Metaprogramming Thoughts

### ISSUE THREAD

**Issue by liamdiprose** [maxeonyx/kal#1]
You mention that you want kal to be syntax agnostic. Have you got any ideas as to what that might look like?

I do!

I've recently picked up the Lisp programming language, which you might be familiar with. Essentially Lisp stands for List Programming, where everything - even the code - is one big datastructure: Lists [1].

This makes it really easy to write macros; functions that take parameters and return code. Because code is just a list, writing a macro is no different to writing a function that returns a list. This gives Lisp the ability to be very meta-programmable very easily. 

The Lisp language can be changed so much, that you can define different paradigms in the language, like Object Oriented. You can even change how variables are resolved, so you can implement different variable scopes, like lexical scope.

I feel like this is the flexibility you talk about when you want kal to be syntax agnostic. There is one problem with Lisp, however. Lisp would not allow you to have the nice Rust/Javascript like syntax; everything in Lisp is a list, which means (everything (is (in (parentheses)))). This is where kal could come in.

If you positioned kal as a syntax-to-Lisp translation, you could possibly get the best of both worlds. Users could write their own grammars for any type of syntax (Rustic/Pythonic/Javascripty) and how they are translated into Lisp. The lisp part would then deal with further translation down to the base AST, as well as deal with variable scope and monomorphization, plus other stuff we don't need to think about yet.

There is still some stuff to sort out, like how different people's grammars work with each other. But I think that if we utilised the power of Lisp, kal could offer a really flexible method of defining new syntax to be used in kal code. 

[1] Ignore numbers and atoms :)

**Comment by maxeonyx** [comment]
Good thoughts here - I have heard of but not used LISP.

Originally was envisioning a generic parser/grammar which is configurable. You would specify the keywords, whitespace settings, statement delimiters etc. in a config file next to your main file, which would be automatically loaded by the runtime. There would also to be the option to recompile the interpreter with the config file built in.

However this will probably make the parser really complicated. Another way I was considering was to make an easy plugin API (in rust, or maybe in kal itself), so that people could redo the grammar.

Some less important goals for me ares the ability to implement a visual scripting language on top of kal, and the ability to write a git merge provider that reduces conflicts when changing/refactoring code.

That last one depends on having similar or identical semantics between syntax variants. Macros and other metaprogramming make this harder, as presenting the user with manual conflicts which are the output of macros could be messy.

Using the lisp model could be cool though- it is very similar to the AST

Do you think there is much difference between compiling to LISP vs. having a stable API for the abstract syntax tree (AST)?

**Comment by liamdiprose** [comment]
The config file you envisioned sounds alot like a grammar file, like the .lalprop file in the project source. This is what I had in mind too - having a grammar description that can be redefined by users.

Close by the grammar description would be a way to define how the captured syntax is converted into a AST. This conversion could be defined within the grammar, like match groups in a regex.

There is no difference between an AST and Lisp. Lisp output would essentially be a textural representation of the AST. As with my initial idea, Lisp would also be useful for transforming the AST into the base AST. Transforming Lisp code into other Lisp code is what Lisp does best.

As a Base AST, we could use the API of a Lisp implementation. There are many Lisp implementations. If you want compile the programs, CHICKEN would be a solid bet as it compiles into a binary via C. Chez Scheme runs quickly on it's interpreter which has a JIT. Clojure would be kal's gateway into the JVM.

It would be best to stick to one implementation for now, as they do things a little differently. CHICKEN would be a good bet, as it could be compiled and used within the Rust interpreter. CHICKEN can also be interpreted in case you're wondering.

When I first thought of custom syntax, I too thought of it as a compiler extension. But wouldn't it be so much cooler if syntax extensions were the same as regular libraries?

`use syntax::python;` and boom, `def main():` becomes valid syntax. I can't think of any reasons where this adds too much complexity. It makes it harder to 'compile in' the syntax to the interpreter...but doesn't make it impossible.

These syntax libraries will define grammar and AST transformations needed. I'm not sure how that would gel with normal libraries that just add code. I guess this is the type of devil we invite when we discard a fixed syntax.

Taking a step back, because Lisp and the AST are the same, you could also wait until later before you utilize Lisp. Depends on what your goals you have for kal. But if your goal is always to target an AST, your project will always be compatible with my Lisp idea. I do think that your goals for kal do overlap with Lisp quite a bit though ;).

I don't think metaprogramming will complicate semantic merge feature much, or maybe I misunderstand how you put it. I'm guessing want the merge-tool to be able to take a diff (from git diff) and tell the unimportant changes like whitespace and variable renames from the important ones like new methods etc. I'm assuming most of the merge logic is performed on the AST level? The important details of the code would be more apparent in the AST, and would be easier to reason about and perform merges. The output of macros wouldn't show up in a diff because macros are only expanded at run time, never in the code.

Having changeable syntax could pose some minor problems with semantic merge. Changing the syntax definition could complicate how the semantics are extracted from the diffs. Put another way, you'd need to tell that these two functions are equivalent:

```python
def do(self, name):
```

and

```rust
pub fn do(&self, name: String) {
```
But I personally don't think its that important, it will just default to "a function was removed and another was added". 

My biggest concern with the Lisp idea is Lisp itself. For the last three days I've tried to get a small demo working, where a C++ class layout can be translated into standard Scheme object oriented code. Still working on it. I got stuck on CHICKEN's 'hygienic macros', which prevents some issue found in common lisp, but seems like a hideous hack to me at the moment.

```scheme
(define-syntax println!
  (er-macro-transformer                   ;;  <-- wtf
      (lambda (form, rename, compare?)
          (println! fmt ...)
          (printf fmt ...))))
```

I'm sure in time I'll come to understand the motivation for hygienic macros, or why `er-macro-transformer` is needed. But it raises a point. If we are going to use Lisp, we will probably need to learn Lisp to the god level. I can see adding a type system being an uphill battle; understanding the absolute lowest level of Lisp will probably be necessary. I'm concerned it will change the scope of your project quite a bit, especially compared to the work you've done so far.

I'm happy to learn Lisp to the max. You've rekindled my interest in language design again, and I feel there's alot I can learn from Lisp. Lisp seems to be pretty pure at its heart, everything seems to be a lambda. But its syntax isn't as good as some others (Rust's match statement :heart: )

Kal could be the (syntax)sugary coating on top of Lisp that makes Lisp much more palatable. Although it does depend on what your goals were for this project, the last thing I want to do is hijack your own project and make you abandon :worried: .

**Comment by maxeonyx** [comment]
Since I havent used lisp before, this all seems a bit magic to me. Am I right on assuming that to use LISP like this I would have to write my interpreter on top of a LISP (like chicken) (which could itself be embedded in rust maybe?). I would prefer interpreter to be written in rust if at all possible. This will let me control the underlying language features/runtime more precisely than using a higher level language. (Although having access to a garbage collector would be great- do you know of any good garbage-collector-as-a-library projects that are usable in rust?)

I would definitely make a lisp-like syntax for the AST (as you say they are the same)

Regarding the `use syntax <>` functionality, that is an interesting thought. It is a bit weird because that line itself must be supported in all syntax implementations, or part of a greater syntax. I think I still prefer the config file. Perhaps the config file can delegate to a library? (Making the config file only 3 or so lines long).

You are right about the semantic merge feature working on the AST - but if your language variant supports more stuff than the AST itself, then how do you nicely present the user with a conflict, when all you have is the conflict in terms of compiled AST?

In any case this is all wishlist stuff :) I'm not sure of my priorities but I think I would rather get built in monads like async/await going before I start on the wierd stuff like this.

**Comment by liamdiprose** [comment]
> Since I havent used lisp before, this all seems a bit magic to me.

Yes, same here, admittedly. I'm still figuring out the pros and cons of lisp, but so far its proving to be very pragmatic. It doesn't take long to build up abstractions, and can lead to some very clear, declarative code. I'm still unsure how to change the underlying stuff like variable lookup though. I'm almost certain it can be done though.

> Am I right on assuming that to use LISP like this I would have to write my interpreter on top of a LISP (like chicken)

This is the after-thought I had. Using an existing LISP implementation would be a good way to bootstrap an interpreted language quickly. You could focus on the higher level language features without having to bother with the lower-level details.

> ...(which could itself be embedded in rust maybe?). I would prefer interpreter to be written in rust if at all possible. This will let me control the underlying language features/runtime more precisely than using a higher level language. 

Sounds like you are interested in the lower level details of the language. You could write the LISP interpreter yourself as well, that way you could have control over the underlying features. I'm not sure how much LISP-specific stuff will need to be in the interpreter if you do go with LISP though.

> Although having access to a garbage collector would be great- do you know of any good garbage-collector-as-a-library projects that are usable in rust?

I haven't heard of that before. I've heard of custom allocators, but I don't think its the same as this.

> I would definitely make a lisp-like syntax for the AST (as you say they are the same)

The correct term for 'lisp-like syntax' is s-expressions. Its exactly the same as WebAssembly's text representation. The nice thing about them is that it makes it easy to use with LISP later on.

> Regarding the use syntax <> functionality, that is an interesting thought. It is a bit weird because that line itself must be supported in all syntax implementations, or part of a greater syntax.

Yea I was thinking about the same thing. My idea for a base syntax would be something that facilitates syntax->lisp conversion. Something like a mixup of LISP and ANTLR4. You could have every installed syntax "register" a use-syntax-line to kal so they can import themselves haha.

>  I think I still prefer the config file. Perhaps the config file can delegate to a library? (Making the config file only 3 or so lines long).

What about this:

```scheme
(import :kal/syntax/easy)
(easy-syntax 
    :indent-style 'tab)
```

Just kidding :stuck_out_tongue: LISP is a nice configuration language though. _Very_ Extendible.

> You are right about the semantic merge feature working on the AST - but if your language variant supports more stuff than the AST itself, then how do you nicely present the user with a conflict, when all you have is the conflict in terms of compiled AST?

If the AST tracked the source tokens (like a line + col range), the AST changes could be tracked back back to the original code. The AST changes might be mangled when they are translated back though, I'm not sure.

> In any case this is all wishlist stuff :) 

Totally fair. I'm planning on starting a few projects in LISP in the near future, so I should be able to disspell some of the magical concepts of LISP and understand how it all works.

The monads you have in mind, both their functionality and their syntax, could be implemented in LISP. But we can always leave the LISP implementation till later if you want to focus on the underlying parts of the interpreter.

:v:
